environment:
  matrix:
    - TOXENV: "2.7"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.4"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.5"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.6"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "3.7"
      TOX_APPVEYOR_X64: 0

    - TOXENV: "2.7"
      TOX_APPVEYOR_X64: 1

    - TOXENV: "3.4"
      TOX_APPVEYOR_X64: 1

    - TOXENV: "3.5"
      TOX_APPVEYOR_X64: 1

    - TOXENV: "3.6"
      TOX_APPVEYOR_X64: 1

    - TOXENV: "3.7"
      TOX_APPVEYOR_X64: 1

build: off

install:
  - "py -3.7 -m pip install -U pip setuptools wheel tox tox-appveyor"

test_script:
  - "py -3.7 -m tox"

cache:
- '%LOCALAPPDATA%\pip\Cache'
